spring:
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    gateway:
      routes:
        - id: question-service
          uri: http://localhost:8081
          predicates:
            - Path=/questions/**
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always